.\"
.\" Copyright (c) 2006-2009
.\" Dominic Fandrey <kamikaze@bsdforen.de>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd April 23, 2009
.Dt BSDADMINSCRIPTS 1
.Os
.Sh NAME
.Nm bsdadminscripts
.Nd perform administrative tasks
.Sh DESCRIPTION
The
.Nm
are a collection of scripts to deal with administrative tasks more
conveniently. Look at the respective manual pages to find out more.
.Ss BUILDFLAGS
Buildflags consists of a configuration syntax for the
.Xr make 1
system normally stored in a file called
.Xr buildflags.conf 1 ,
a converter called
.Xr buildflags.awk 1 ,
which converts the configuration file into make syntax and a make file
.Xr buildflags.mk 1 ,
which can be included into
.Xr make.conf 5
to use the buildflags system.
.Ss DISTVIPER
The distviper script wipes outdated files from the distdir. For this it
provides a fast mode that should be appropriate for most systems and a thorough
default that will also yield satisfying results on a dedicated build machine.
.Ss PKG_LIBCHK
The
.Xr pkg_libchk 1
script uses
.Xr pkg_info 1 ,
.Xr ldd 1
and
.Xr readelf 1
to find packages that are linked against missing libraries or libraries that
reside in %%PREFIX%%/lib/compat and its subfolders.
.Ss PKG_UPGRADE
The
.Xr pkg_upgrade 1
script offers the possibility to perform binary only package maintenance
similar to tools for the FreeBSD ports tree, but only requiring a local copy
of the INDEX created by a build server.
.Ss PKG_VALIDATE
The
.Xr pkg_validate 1
script uses
.Xr pkg_info 1
to check for ports with checksum mismatches or missing files.
.Ss PORTCONFIG
The
.Xr portconfig 1
script runs make targets on the same ports that
.Xr portupgrade 1
would update.
.Ss RCSTART
The
.Xr rcstart 1
script allows you to handle
.Xr rc.d 8
scripts on the fly without
having to know the exact file name. Instead you select them by the PROVIDE
keyword.
.Ss UMA (Update MAnanager)
The
.Xr uma 1
script offers locking and meta data updating services for ports and package
maintenance.
.Sh SEE ALSO
.Xr buildflags.awk 1 ,
.Xr buildflags.conf 1 ,
.Xr buildflags.mk 1 ,
.Xr distviper 1 ,
.Xr pkg_libchk 1 ,
.Xr pkg_upgrade 1 ,
.Xr pkg_validate 1 ,
.Xr portconfig 1 ,
.Xr rcstart 1 ,
.Xr uma 1
.Sh HISTORY
The
.Nm
first appeared on April 12, 2006.
.Sh AUTHOR
Dominic Fandrey <kamikaze@bsdforen.de>
