.\"
.\" Copyright (c) 2009
.\" Dominic Fandrey <kamikaze@bsdforen.de>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd April 23, 2009
.Dt DISTVIPER 1
.Os
.Sh NAME
.Nm distviper
.Nd wipe outdated files from the FreeBSD ports distdir
.Sh SYNOPSIS
.Nm
.Op Fl dhiqv
.Op Ar mode
.Sh DESCRIPTION
The
.Nm
script removes outdated files in %%DISTDIR%%. To achieve this it reads all
files named distinfo from %%PORTS%% and creates a list of files to keep if
they should be encountered. Every file not in this list is deleted.
.Pp
The creation of the list of files to keep can take very long, if the ports
tree is not cached in memory. Because of this there is a fast mode that will
only use distinfo files from installed ports.
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent
.It Fl d -demo
The program is run in demo mode. The program acts as if it would operate
normally, but does not remove any files.
.It Fl h -help
Displays the available options.
.It Fl i -interactvie
This option prompts for confirmation before deleting a file.
It is ignored in demo mode.
.It Fl q -quiet
Supresses delete messages.
.It Fl v -verbose
Makes the script talkative about what is currently going on.
.It Ar mode
There are currently two modes available. By default the thorough mode is
selected, which scans all distinfo files. The fast mode only scans distinfo
files for installed ports.
.El
.Sh NOTES
The fast mode is often sufficient. There are two cases when this does not
apply.
.Pp
If one intends to keep distfiles for ports that are not currently installed,
like on a dedicated build machine, the (default) thorough mode is the mode of
choice.
.Pp
The other case is, when a port fetches its files by having a dependency on the
fetch target of another port and this other port is not installed. This is
a very rare case, though.
.Sh EXAMPLES
To run the script in thorough mode use the following command line.
.Bd -literal -offset indent
distviper
.Ed
.Pp
The demo mode can be used to check which files would be removed in fast mode.
.Bd -literal -offset indent
distviper -d fast
.Ed
.Pp
To be prompted for confirmation and using fast mode the following line
can be used.
.Bd -literal -offset indent
distviper -i fast
.Ed
.Pp
.Sh EXIT CODES
.Bl -tag -width indent
.It 1
An unknown parameter has been supplied.
.It 2
An unknown mode command has been supplied.
.It 3
More than one mode commands have been supplied.
.El
.Sh COMPATIBILITY
The script has been tested on FreeBSD 7.2-PRERELEASE.
.Sh SEE ALSO
.Xr bsdadminscripts 1
.Sh HISTORY
The
.Nm
script first appeared in the bsdadminscripts-5.0 collection.
.Sh AUTHOR
Dominic Fandrey <kamikaze@bsdforen.de>
