.\"
.\" Copyright (c) 2007-2009
.\" Dominic Fandrey <kamikaze@bsdforen.de>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd April 23, 2009
.Dt PKG_LIBCHK 1
.Os
.Sh NAME
.Nm pkg_libchk
.Nd check packages for links against missing libraries
.Sh SYNOPSIS
.Nm
.Op Fl achmnoqrRv
.Op Ar packages
.Sh DESCRIPTION
The
.Nm
script uses
.Xr pkg_info 1 ,
.Xr ldd 1
and
.Xr readelf 1
to check whether a package is linked against missing libraries or libraries
residing in %%PREFIX%%/lib/compat and its subfolders.
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent
.It Fl a -all
Check all packages. This is the default action in case no packages have been
specified.
.It Fl c -clean
Create clean output without status messages.
.It Fl h -help
Displays the available options.
.It Fl jN -jobsN
Specify the amount of parallel jobs the script will attempt run. The default is
two jobs per CPU core.
.It Fl m -mean
In this mode all the checks to detect false positives are turned off. This
has several effects. Packages like OpenOffice which do not rely on the OS
to find their libraries will yield lots of hits.
.Pp
Also indirect dependencies will be printed. The difference is that this way
the packages currently inoperable will be returned instead of the packages
that need to be rebuild in order to fix the damage.
.Pp
Running the script in mean mode reduces the run time by approximately 15%.
.It Fl n -no-compat
This deactivates detecting compat libraries in %%PREFIX%%/lib/compat
as missing libraries.
.It Fl o -origin
Instead of the package name the package origin is printed.
.It Fl q -raw
Only print the names of affected packages. Do not print any details. This
option is meant for machine readability. It also speeds up operation on
affected packages, because it allows the script to move to the next package
without checking the whole package.
.Pp
This option cannot be combined with verbose output.
.It Fl r -recursive
Also check packages the given packages depend on.
.It Fl R -upward-recursive
Also check the packages depending on the given packages.
.It Fl v -verbose
Be verbose about missing dependencies. Instead of rejecting indirect
dependencies or false positives it will print why they would have been
rejected.
.Pp
This option cannot be combined with raw output.
.It Ar packages
Packages are package names or shell patterns matching these.
.El
.Sh NOTES
Some packages like OpenOffice or Java environments always miss some libraries,
this is because they have their own ways of finding libraries.
.Pp
This output can be suppressed by adding the following lines to the file
/etc/libmap.conf:
.Bd -literal -offset indent
# Clean up pkg_libchk output.
[libofficebean.so]
libjawt.so	libc.so

[libJdbcOdbc.so]
libodbcinst.so	libc.so
libodbc.so	libc.so
.Ed
.Sh SORTED OUTPUT
Since the possibility to run parallel jobs was introduced, output no longer
is sorted. If you find that annoying you can run:
.Bd -literal -offset indent
pkg_libchk -j1
.Ed
.Pp
Of course there is a heavy performance penalty especially on systems with
several CPU cores.
.Pp
Another way around this is to pipe output into
.Xr  sort 1 :
.Bd -literal -offset indent
pkg_libhck | sort
.Ed
.Pp
This will run faster, but output will be printed after the script has
terminated.
.Sh EXAMPLES
To check all your packages run:
.Bd -literal -offset indent
pkg_libchk
.Ed
.Pp
To create raw output for everything connected to gtk.
.Bd -literal -offset indent
pkg_libchk -q \\*gtk\\*
.Ed
.Pp
After upgrading a library, in this case icu, you can check all depending
packages:
.Bd -literal -offset indent
pkg_libchk -R icu-\\*
.Ed
.Sh EXIT CODES
.Bl -tag -width indent
.It 1
An unknown parameter has been supplied.
.It 2
The incompatible parameters
.Fl v
and
.Fl q
have been supplied.
.It 3
The parameter
.Fl j
has been supplied without an acceptable number.
.It 255
The script has terminated because it received SIGINT or SIGTERM.
.El
.Sh COMPATIBILITY
The script has been tested on FreeBSD 7.2-PRERELEASE.
.Sh SEE ALSO
.Xr bsdadminscripts 1 ,
.Xr pkg_info 1 ,
.Xr ldd 1 ,
.Xr readelf 1
.Sh HISTORY
The
.Nm
script first appeared in the bsdadminscripts-4.0 collection.
.Sh AUTHOR
Dominic Fandrey <kamikaze@bsdforen.de>
