.\"
.\" Copyright (c) 2006-2009
.\" Dominic Fandrey <kamikaze@bsdforen.de>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd April 23, 2009
.Dt PORTCONFIG 1
.Os
.Sh NAME
.Nm portconfig
.Nd run
.Xr make 1
targets on
.Xr ports 7
that need updating
.Sh SYNOPSIS
.Nm
.Op Fl vafrRh
.Op Fl tN
.Op Ar ports
.Sh DESCRIPTION
The
.Nm
script was written to issue make targets to a number of ports
instead of going into every ports folder and running the command by
hand. The make target issued is determined from the scriptname minus
the 'port' prefix. Different targets can be realized by creating links.
.Pp
The following aliases are available:
.Bl -tag -width indent
.It Fr portconfig portbuild portclean portfetch portpackage \
portconfig-recursive portfetch-recursive
.El
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent
.It Fl v -verbose
Be verbose.
.It Fl a -all
Act on all ports that require updating. Or on all installed ports if
.Fl f
is given.
.It Fl f -force
Also acts on ports that do not require updating and ports that are not
yet installed.
.It Fl r -recursive
Act on depending ports as well.
.It Fl R -upward-recursive
Act on ports the given ports depend on as well.
.It Fl tN -try-againN
If the target returns an error try again for N times. N is a value from
0 to 9.
.It Fl h -help
Displays the available options.
.It Ar ports
The last parameter is a list of ports to act on, either in the category/port
format or the package name of an installed package.
.El
.Sh EXAMPLES
If you want to see the config dialogues of all ports that require updating
prior to running 'portupgrade -a' the following line will achieve this:
.Bd -literal -offset indent
portconfig -a
.Ed
.Pp
If you want to see the config dialogues of new dependencies as well run the
following command:
.Bd -literal -offset indent
portconfig-recursive -a
.Ed
.Sh EXIT CODES
.Bl -tag -width indent
.It 1
An unknown parameter has been supplied.
.It 2
The parameter -t has been supplied without a number.
.El
.Sh COMPATIBILITY
The script has been tested on FreeBSD 7.2-PRERELEASE.
.Sh SEE ALSO
.Xr bsdadminscripts 8 ,
.Xr ports 7
.Sh HISTORY
The
.Nm
script first appeared in the bsdadminscripts-0.9 collection.
.Sh AUTHOR
Dominic Fandrey <kamikaze@bsdforen.de>
