.\"
.\" Copyright (c) 2006-2009
.\" Dominic Fandrey <kamikaze@bsdforen.de>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd April 23, 2009
.Dt RCSTART 1
.Os
.Sh NAME
.Nm rcstart 
.Nd use
.Xr rc.d 8
scripts conveniently
.Sh SYNOPSIS
.Nm
.Op Fl vnpslh
.Op Ar services
.Sh DESCRIPTION
The
.Nm
script was written to give easier access to init scripts in the
.Xr rc.d 8
folders. The parameter given to those scripts is its own name
minus the 'rc' prefix. Different parameters are realized by creating links.
.Pp
The following aliases are available:
.Bl -tag -width indent
.It Fr rcstart rcstatus rcstop rcrestart
Use services that have service_enable="yes" set.
.It Fr rconestart rconestatus rconestop rconerestart
Use services that do not have service_enable="yes" set.
.El
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent
.It Fl v -verbose
Be verbose after this parameter.
.It Fl n -not-verbose
Do not be verbose after this parameter.
.It Fl p -paths
Display the paths that are scanned for init scripts.
.It Fl s -services
Display all available services.
.It Fl l -locate
Following this parameter scripts will not be executed, but their location
will be printed until
.Fl n
or
.Fl v
appear.
.It Fl h -help
Displays the available options.
.It Ar services
A service is provided by an init script in an rc.d folder. The name of the
service provided by an rc.d script can be identified through the PROVIDE
keyword.
.Pp
The
.Ar services
parameter is treated as a regular expression by the
.Nm
script.
.El
.Sh EXAMPLES
To restart all SQL servers simply run:
.Bd -literal -offset indent
rcrestart '.*sql'
.Ed
.Pp
If the servers have no respective entries in /etc/make.conf,
the command has to look like this:
.Bd -literal -offset indent
rconerestart '.*sql'
.Ed
.Sh COMPATIBILITY
The script has been tested on FreeBSD 7.2-PRERELEASE.
.Sh SEE ALSO
.Xr bsdadminscripts 1
.Sh HISTORY
The
.Nm
script first appeared in the bsdadminscripts-0.9 collection.
.Sh AUTHOR
Dominic Fandrey <kamikaze@bsdforen.de>
