.\"
.\" Copyright (c) 2009
.\" Dominic Fandrey <kamikaze@bsdforen.de>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd Nov 10, 2009
.Dt UMA 1
.Os
.Sh NAME
.Nm uma
.Nd package and ports  meta data updating and locking facility
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Ar pid
.Op env
.Op fetch
.Op extract
.Op update
.Op Ar ...
.Nm uma
.Op Fl hv
.Op Ar pid
.Op env
fetch
.Op ports
.Op audit
.Op ftpindex
.Nm
.Op Fl hv
.Op Ar pid
.Op env
extract
.Op ports
.Nm
.Op Fl hv
.Op Ar pid
.Op env
update
.Op ports
.Nm
.Op Fl hv
lock
.Op Ar pid
.Nm
.Op Fl hv
unlock
.Op Ar pid
.Sh DESCRIPTION
The
.Nm
script is a locking and meta data updating facility for package management
tools. It is not primarily designed for human use, but it might still be
handy occasionally, especially in environments with several system
administrators.
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent
.It Fl v -verbose
Activates error output. Without this flag errors are only silently
reported with the return value.
.It Fl h -help
Prints the available command parameters.
.It Ar pid
A numerical value representing a process id. This can be used to identify
the caller as the lock owner.
.It env
Causes uma to print some environment variables in an executable format. Some
of them are actively set by uma if not present. E.g. 
.Ar PACKAGESITE .
.It fetch
The fetch command for several targets.
.It extract
The extract command, only applicable to the ports target.
.It update
The update command, only applicable to the ports target.
.It audit
The audit target, can be used to fetch a new
.Xr portaudit 1
database. This only works if "ports-mgmt/portaudit" is installed.
.It ftpindex
This target can be used with the fetch command to fetch the INDEX, MOVED and
UPDATING files from the location provided by
.Ar PACKAGESITE.
.It ports
This target can be used with the fetch, update and extract commands. It works
by calling
.Xr portsnap 8 .
.El
.Sh IMPLEMENTATION NOTES
Most of the commands provided by
.Nm
exist for the sake of convenience. The only noteworthy features are the
.Ar env
argument and the locking.
.Ss LOCKING
Apart from
.Fl h
and
.Ar env
all
.Nm
commands are only executed if a lock is held or can be acquired. By
providing
.Ar pid
a command can be run for a different process.
.Pp
If a lock is explicitely requested via the
.Ar lock
argument, it will be held until the process specified with
.Ar pid
terminates or the
.Ar unlock
command is called. If the
.Ar lock
or
.Ar unlock
command is supplied, all others will silently be ignored. the
.Ar unlock
command has preference over
.Ar lock .
.Ss ENV
The env lists the values of the environment variables
.Ar ARCH , BRANCH , PACKAGEROOT , PACKAGEROOT_MIRRORS , PACKAGESITE ,
.Ar PACKAGESITE_MIRRORS , FTP_PASSIVE_MODE , FTP_TIMEOUT ,
.Ar PKG_INDEX , PKG_MOVED
and
.Ar PKG_UPDATING
in an executable format. The noteworthy part is that
.Nm
attempts to set reasonable default values for variables that are not set.
.Pp
Other programs like
.Xr pkg_upgrade 1
can use this to acquire a sensible
.Ar PACKAGESITE
value, if only
.Ar PACKAGEROOT
or even neither one is set in the environment.
.Sh EXAMPLES
The following command downloads the current INDEX, MOVED and UPDATING files
from a FreeBSD package building server:
.Bd -literal -offset indent
uma fetch ftpindex
.Ed
.Pp
The following command can be used by a system administrator to block all
uma using applications:
.Bd -literal -offset indent
uma -v lock $$
.Ed
.Pp
This creates a lock for the current terminal session. If all system
administrators use this command this is a simple way of telling each other
that system maintainance is being performed and the system should be left
alone.
.Pp
The lock can be freed by closing the terminal or by running the following
command in the same terminal:
.Bd -literal -offset indent
uma -v unlock $$
.Ed
.Sh ENVIRONMENT
Certain aspects of the
.Nm
utility and several of the underlying applications can be configured by
setting environment variables. Alternatively these variables can be set
in the configuration file "%%PREFIX%%/etc/uma.conf".
.Bl -tag -width indent
.It Ar ARCH
The current processor architecture. This is used to construct
.Ar PACKAGESITE .
.Pp
It defaults to the output of "uname -m".
.It Ar BRANCH
The system branch, this is used to construct
.Ar PACKAGESITE .
.Pp
The default is system dependent. E.g. "7-stable", "7.2-release", "8-current".
.It Ar FTP_PASSIVE_MODE
This can be used to turn passive FTP on and off. This is useful to get
through certain firewall settings.
.Pp
The default is "yes", set it to "no" to turn passive FTP off.
.It Ar FTP_TIMEOUT
The time out time in seconds used by
.Xr fetch 1
when downloading the index.
.Pp
The default is "60".
.It Ar PACKAGEROOT
The server to download the INDEX from.
.Pp
It defaults to "ftp://ftp.freebsd.org".
.It Ar PACKAGEROOT_MIRRORS
A list of server mirrors either separated by line feeds or semicolons. Note
that semicolons will be converted to line feeds.
.Pp
Defaults to the primary FreeBSD mirrors.
.It Ar PACKAGESITE
The location of the "Latest" directory on the server. Also separated by line
feeds or semicolons that get converted to line feeds.
.Pp
It defaults to "$PACKAGEROOT/pub/FreeBSD/ports/$ARCH/packages-$BRANCH/Latest".
.It Ar PACKAGESITE_MIRRORS
The location of the "Latest" directory on the mirrors.
.Pp
Defaults to the primary FreeBSD mirrors.
.It Ar PKG_INDEX
This names the location to store the downloaded INDEX file. It defaults to
"%%VAR%%/db/uma/FTPINDEX".
.It Ar PKG_MOVED
This names the location to store the downloaded MOVED file. It defaults to
"%%VAR%%/db/uma/FTPMOVED".
.It Ar PKG_UPDATING
This names the location to store the downloaded UPDATING file. It defaults to
"%%VAR%%/db/uma/FTPUPDATING".
.El
.Sh FILES
.Nm
uses and creates a number of files and directories.
.Bl -tag -width indent
.It %%PREFIX%%/etc/uma.conf
The configuration file to set environment variables.
.It %%PREFIX%%/etc/uma.conf.sample
A file with example configurations.
.It $PKG_INDEX
This is the location of the downloaded INDEX file.
.It $PKG_MOVED
This is the location of the downloaded MOVED file.
.It $PKG_UPDATING
This is the location of the downloaded UPDATING file.
.It %%VAR%%/run/uma.lock
The location of the file that is locked on.
.It %%VAR%%/run/uma.pid
The PID file of the lock holding process.
.It %%VAR%%/run/uma.ident.pid
The file containing the PID of the lock owner.
.El
.Sh EXIT CODES
The
.Nm
script has both fatal and non-fatal errors. In order to be able to report
several errors at once, the return value is treated as a bit mask. Because
the return value is only a byte this is limited to eight different possible
errors.
.Pp
The following table lists the possible errors and their bit positions.
.Bl -tag -width indent
.It ERR_LOCK 0
The first bit represents a locking error. Locking errors are fatal.
.It ERR_ARG 1
The second bit is set for unknown arguments. This error is fatal.
.It ERR_FETCH_PORTS 2
The third bit is set if
.Nm
was unable to fetch the ports tree.
.It ERR_FETCH_VULNDB 3
The fourth bit is set if
.Nm
was unable to fetch the vulnerability database.
.It ERR_FETCH_INDEX 4
The fifth bit is set if
.Nm
was unable to fetch the INDEX, MOVED or UPDATING file from a server.
.It ERR_EXTRACT_PORTS 5
The sixth bit is set if the ports tree could not be extracted.
.It ERR_UPDATE_PORTS 6
The seventh bit is set if the ports tree could not be updated.
.El
.Sh COMPATIBILITY
The script has been tested on FreeBSD 7.2-STABLE.
.Sh SEE ALSO
.Xr bsdadminscripts 1 ,
.Xr pkg_upgrade 1 ,
.Xr fetch 1 ,
.Xr portsnap 8 ,
.Xr portaudit 1
.Sh HISTORY
The original idea, together with a specification draft, originates from
Hannes Hauswedell, originator of the KPorts project and a member of the
BSDForen.de team.
.Pp
The
.Nm
script first appeared in the bsdadminscripts-6.0 collection.
.Sh AUTHOR
Dominic Fandrey <kamikaze@bsdforen.de>
